### ISSUE TITLE
Top-margin causing interaction and interface issues

### ISSUE THREAD

**Issue by zinzy** [vhbelvadi/obsidian-carbon#1]
Thanks for this lovely theme, @vhbelvadi! My colleague and I are quite the fans of it. We've noticed two small quirks.

```
.markdown-source-view.mod-cm6 .cm-line {
	margin-top: 0.1rem !important;
}
```

This style definition results in:
1. The user being unable to select words in the last line of a document (bar the very last word)
2. Separators between lines in a code block (I'm following [Carbon design guidelines](https://carbondesignsystem.com/components/code-snippet/usage/) here to suggest this isn't strictly necessary)

I've already added this to my Obsidian snippets and I haven't noticed anything weird so far, so I went ahead and [created a pull request](https://github.com/vhbelvadi/obsidian-carbon/pull/2) as well.

**Comment by vhbelvadi** [comment]
@zinzy Thanks so much for this, and I'm glad you're both enjoying the theme. I haven't had much time (till now) to drop by Github and look into issues/pull requests. I've merged your changes now though—sorry for the delay.

**Comment by vhbelvadi** [comment]
@zinzy Thanks so much for this, and I'm glad you're both enjoying the theme. I haven't had much time (till now) to drop by Github and look into issues/pull requests. I've merged your changes now though—sorry for the delay.
